song_list = ['Numenorean - Coma', 'Numenorean - Stay', 'Numenorean - Alone', 'Numenorean - Adore', 'Bxmmusic - Brandon',
             'Andreas Rönnberg - First Station', 'Andreas Rönnberg - Lonely', 'Andreas Rönnberg - Hurt',
             'Intig - C17h27no2', 'Intig - In a Better Place', 'Intig - Falling', 'Apati - Morgondagen',
             'Burzum - Erblicket Die Tochter Des Firmaments', 'Veil - Mater Maternis', "Happy Days - Don't Go",
             'Thy Light - In My Last Mourning... - 2012 Remaster', 'Nargaroth - Seven Tears Are Flowing To The River',
             'Totalselfhatred - Enlightment', 'None - Hypoxic',
             'Thy Light - A Crawling Worm in a World of Lies - 2012 Remaster', 'Deftones - Rosemary',
             'Deftones - Minerva', 'Deftones - Entombed', 'Deftones - My Own Summer (Shove It)',
             'Deftones - Dai the Flu', 'Exiled from Light - There Is No Beauty Left Here...',
             'Suizid - I Left This Life To Rot', 'Intig - Søvnløshed', 'Exiled from Light - We Writhe as Worms',
             'Wedard - Einsamer Winterweg', 'Make A Change... Kill Yourself - Shadows of a meaningless reality',
             "Nae'blis - Sketches Of Reality", 'Aldaaron - Lord of Winter', 'Intig - Life Wasted',
             'Intig - In the Stream of Killing Everything', 'Xasthur - Screaming at Forgotten Tears',
             'Numenorean - Home']
